root:
  foil: airfoils/ht22.dat
  chord: 100
  washout: 0
  sweep: 0
  lift: 0
  
tip:
  foil: airfoils/ht22.dat
  chord: 100 
  washout: 0
  sweep: 0
  lift: 0

kerf: 0.55
towerX_dist: 110
towerU_dist: 150
block_width: 25.5

margin: 5
travel_height: 50
  #block_height: 30

feed_rate: 100



