root:
  foil: airfoils/naca0015.dat
  chord: 100
  washout: 0
  sweep: 0
  lift: 0
  
tip:
  foil: airfoils/naca0015.dat
  chord: 70          
  washout: 0
  sweep: 30
  lift: 0

kerf: 0.55
block_width: 150
towerX_dist: 245
towerU_dist: 272

margin: 10
travel_height: 70

feed_rate: 100



